In [38]:
from urllib.request import urlopen
import numpy as np


f = urlopen("https://stepic.org/media/attachments/lesson/16462/boston_houses.csv")
mat = np.loadtxt(f, skiprows = 1, delimiter = ",")
print(mat, "\n")
print(mat.mean(axis = 0))





[[2.4000e+01 6.3200e-03 1.8000e+01 ... 5.3800e-01 6.5750e+00 4.0900e+00]
 [2.1600e+01 2.7310e-02 0.0000e+00 ... 4.6900e-01 6.4210e+00 4.9671e+00]
 [3.4700e+01 2.7290e-02 0.0000e+00 ... 4.6900e-01 7.1850e+00 4.9671e+00]
 ...
 [2.3900e+01 6.0760e-02 0.0000e+00 ... 5.7300e-01 6.9760e+00 2.1675e+00]
 [2.2000e+01 1.0959e-01 0.0000e+00 ... 5.7300e-01 6.7940e+00 2.3889e+00]
 [1.1900e+01 4.7410e-02 0.0000e+00 ... 5.7300e-01 6.0300e+00 2.5050e+00]] 

[22.53280632  3.61352356 11.36363636  0.06916996  0.55469506  6.28463439
  3.79504269]
