In [1]:
import numpy as np

x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

3 2
1 1 1 10 10 1
3 1
10 7 12


[[ 1  1]
 [ 1 10]
 [10  1]]


In [118]:
if (x_shape[1] == y_shape[1]):
    print (X.dot(Y.T));
else:
    print ("matrix shapes do not match");

[[ 82  96 108  78]
 [ 96 114 108  66]]


[[5 5 3 1]
 [5 2 3 4]
 [1 6 9 6]]
