In [2]:
import numpy as np


In [8]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(13,25).reshape(3,4)
print(a, '\n')
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [54]:
X = np.random.randint(high = 10, low = 1, size = 30).reshape(5,6)
W = np.zeros((5,2), dtype = int)
W += 1;

print(X, '\n')
print(W)


[[1 8 1 2 3 4]
 [5 9 5 4 7 7]
 [4 1 9 3 4 6]
 [7 2 9 7 1 8]
 [2 1 2 6 2 2]] 

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [55]:

y = W.T.dot(X).T
print(y)


[[19 19]
 [21 21]
 [26 26]
 [22 22]
 [17 17]
 [27 27]]
