In [99]:
import numpy as np

print (np.eye(5,3, k = 1))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print (np.array([[1,2,3], [4,5,6]]))


[[1 2 3]
 [4 5 6]]


In [101]:
print (np.zeros((10,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [103]:
print (np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
print (np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [89]:
a = np.full((5,5),2)
a[2][1:3]= 5
print (a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 5 5 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [91]:
a[-1][0:5:3] = 7
print (a);

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 5 5 2 2]
 [2 2 2 2 2]
 [7 2 2 7 2]]


In [98]:
a[..., 4] = 8;
print (a)

[[2 2 2 2 8]
 [2 2 2 2 8]
 [2 5 5 2 8]
 [2 2 2 2 8]
 [7 2 2 7 8]]
