In [14]:
import numpy as np


x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(float, input().split()), np.float).reshape(x_shape)
print(X)
y_shape = int(input())
Y = np.fromiter(map(float, input().split()), np.float).reshape(y_shape,1)
print(Y)

W = [0,0,0]
print(W)

3 3
1 1 0.3 1 0.4 0.5 1 0.7 0.8
[[1.  1.  0.3]
 [1.  0.4 0.5]
 [1.  0.7 0.8]]
3
1 1 0
[[1.]
 [1.]
 [0.]]
[0, 0, 0]


In [15]:

perfect = False
while perfect != True:
    k = 0
    perfect = True
    for e in X:
        answer = np.sum(e * W, 0)
        print("e: ", e)
        print("answer: " , answer)
        print("Y[", k, "][0]: ", Y[k][0])
        if (answer > 0): answer = 1
        else: answer = 0
        if answer != Y[k][0]:
            perfect = False
            if answer == 0:
                W = W + e
            else:
                W = W - e
        print("w: ", W)      
        k += 1
    print(W)
    

e:  [1.  1.  0.3]
answer:  0.0
Y[ 0 ][0]:  1.0
w:  [1.  1.  0.3]
e:  [1.  0.4 0.5]
answer:  1.5499999999999998
Y[ 1 ][0]:  1.0
w:  [1.  1.  0.3]
e:  [1.  0.7 0.8]
answer:  1.94
Y[ 2 ][0]:  0.0
w:  [ 0.   0.3 -0.5]
[ 0.   0.3 -0.5]
e:  [1.  1.  0.3]
answer:  0.15000000000000005
Y[ 0 ][0]:  1.0
w:  [ 0.   0.3 -0.5]
e:  [1.  0.4 0.5]
answer:  -0.12999999999999998
Y[ 1 ][0]:  1.0
w:  [1.  0.7 0. ]
e:  [1.  0.7 0.8]
answer:  1.49
Y[ 2 ][0]:  0.0
w:  [ 0.00000000e+00  1.11022302e-16 -8.00000000e-01]
[ 0.00000000e+00  1.11022302e-16 -8.00000000e-01]
e:  [1.  1.  0.3]
answer:  -0.23999999999999988
Y[ 0 ][0]:  1.0
w:  [ 1.   1.  -0.5]
e:  [1.  0.4 0.5]
answer:  1.15
Y[ 1 ][0]:  1.0
w:  [ 1.   1.  -0.5]
e:  [1.  0.7 0.8]
answer:  1.2999999999999998
Y[ 2 ][0]:  0.0
w:  [ 0.   0.3 -1.3]
[ 0.   0.3 -1.3]
e:  [1.  1.  0.3]
answer:  -0.08999999999999997
Y[ 0 ][0]:  1.0
w:  [ 1.   1.3 -1. ]
e:  [1.  0.4 0.5]
answer:  1.02
Y[ 1 ][0]:  1.0
w:  [ 1.   1.3 -1. ]
e:  [1.  0.7 0.8]
answer:  1.10999999999999