In [1]:
import numpy as np

In [97]:
mat = np.zeros((3,4)) + np.eye(3,4) * 2 + np.eye(3,4,1);
print(mat)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [107]:
now = mat.reshape(12,1)
print (now);

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [108]:
print (mat.flatten()[None].T)


[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [109]:
print (mat.flatten()[:, None])

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]
